version: "3.3"

services: 
  albumviewer: 
    image: sofdreg002.azurecr.io/schoolofdevops/albumviewer
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:80
    environment: 
      - "Data:Provider=MySQL"
      - "Data:ConnectionString=Server=database;Port=4000;Database=AlbumViewer;User=root;SslMode=None"

  database: 
    image: dockersamples/tidb:nanoserver-sac2016